### ISSUE TITLE
Add comments to pairings

### ISSUE THREAD

**Issue by rfrovarp** [NDSU-Information-Technology/international-capstone-exchange#16]
We should be able to add a chain of comments to pairings.

Comments can be added by either individuals in the pairing, or anyone with an admin role.
Comments are visible by anyone who can post a comment to the pairing, so either individual or any admins.
User's can delete their own comment. There should be a restriction so that an admin posted comment can't be deleted by that user if there are no longer an admin.

**Comment by TimMarshalHunter** [comment]
This appears to have already been implemented.
