### ISSUE TITLE
Changing wording from proposal to pairing

### ISSUE THREAD

**Issue by rfrovarp** [NDSU-Information-Technology/international-capstone-exchange#18]
To repeat, can you change Proposal Request/Create Proposal/Proposal/etc. to Pairing Request/Create Pairing Request/Pairing Request/etc. throughout the application?  I think it would be more clear to the users.

**Comment by TimMarshalHunter** [comment]
I think this one was done? There at least seems to be a clear distinction between the use of Proposal vs. Pairing.
